### 密码模式获取JWT令牌
POST {{auth_host}}/oauth/token?client_id=qbWebApp&client_secret=qbWebApp&grant_type=password&username=16606258160&password=Root_1234

### 校验JWT令牌中的信息
POST {{auth_host}}/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicWlhbi1iaWFuIl0sInVzZXJfbmFtZSI6IntcImlkXCI6MSxcInBob25lXCI6XCIxNjYwNjI1ODE2MFwiLFwiYXZhdGFyVXJpXCI6XCIvZGVmYXVsdC91c2VyX2RlZmF1bHQucG5nXCIsXCJuaWNrTmFtZVwiOlwiemhpbWFcIixcImFnZVwiOjE5LFwiZW1haWxcIjpcIjExNTg3Nzg2ODlAcXEuY29tXCIsXCJzZXhcIjoxLFwiZGVmYXVsdEFkZHJlc3NJZFwiOjAsXCJuYW1lXCI6XCLmnY7mmbpcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc1NzAxODc1LCJhdXRob3JpdGllcyI6WyJyb290Il0sImp0aSI6IjViZWQ0YzI0LTIwMTQtNGMxMi05OTgxLTkyZTg3ZjA3MDM4OSIsImNsaWVudF9pZCI6InFiV2ViQXBwIn0.YZV__2C1jWXUICnqN0Cv5RK-Jdn0KHY6RdSgI3lkqtQ