### 返回生成的用来支付的大订单的编号，返回订单编号
POST {{gateway_order_host}}/merchandise-order/generate
Authorization: Bearer {{access_token}}
Content-Type: application/json

[
  {
    "shopId": 1,
    "total": 20.5,
    "actualTotal": 20.5,
    "deliveryAddress": "江苏省苏州市太仓市",
    "merchandises": [
      {
        "id": 1,
        "quantity": 1,
        "unitPrice": 20.5
      }
    ]
  },
  {
    "shopId": 2,
    "total": 30.4,
    "actualTotal": 30.4,
    "deliveryAddress": "江苏省苏州市太仓市",
    "merchandises": [
      {
        "id": 2,
        "quantity": 1,
        "unitPrice": 30.4
      }
    ]
  }
]

### 得到支付的body体，前端的地址直接写这个地址就可以跳转支付界面
GET {{gateway_order_host}}/alipay/20230216153152mbjtyx


### 得到登录用户指定状态的订单，不传就是所有
GET {{gateway_order_host}}/merchandise-order/1
Authorization: Bearer {{access_token}}
