### 测试SecurityUtil是否可以正确获取当前登录用户信息
GET {{user_host}}/footmark/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicWlhbi1iaWFuIl0sInVzZXJfbmFtZSI6IntcImlkXCI6MSxcInBob25lXCI6XCIxNjYwNjI1ODE2MFwiLFwiYXZhdGFyVXJpXCI6XCIvZGVmYXVsdC91c2VyX2RlZmF1bHQucG5nXCIsXCJuaWNrTmFtZVwiOlwiemhpbWFcIixcImFnZVwiOjE5LFwiZW1haWxcIjpcIjExNTg3Nzg2ODlAcXEuY29tXCIsXCJzZXhcIjoxLFwiZGVmYXVsdEFkZHJlc3NJZFwiOjAsXCJuYW1lXCI6XCLmnY7mmbpcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc1NzU5NzA5LCJhdXRob3JpdGllcyI6WyJyb290Il0sImp0aSI6ImVmOGViMWJmLTM2ODUtNDJmYi1hNTg5LWE5M2QxMzcxNjc3ZiIsImNsaWVudF9pZCI6InFiV2ViQXBwIn0.8GjklTpILEuUbd0-Srb0dgpphAAB3qquoCZvKlMOdyE
